name: first workflow

on:
   push:
     branches: [ "main" ]

jobs:

  job1:

    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "hello,wrold! from step5"
      - name: step2
        uses: actions/checkout@v4
  
  job2:

    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: |
           echo "Hello"
           date
           hostname
   
  job3:

    runs-on: ubuntu-latest

    steps:
      - name: step3
        run: |
           ls -al
           uptime
           whoami