# aws auth
# terraform version 1.16.0
# terrafrom path - infra

name: terraform-2tier-ecs

on:
    workflow_dispatch:
        inputs:
            plan_apply_destroy:
                description: "Plan, Apply, or Destroy"
                type: choice
                required: true
                default: "plan"
                options:
                    - plan
                    - apply
                    - destroy

concurrency:
  group: terraform-2tier-ecs
  cancel-in-progress: false

env:
    TF_VERSION: 1.16.0
    TF_PATH: terraform-2tier-ecs/infra
    AWS_REGION: us-east-1
jobs:
    terraform-plan:
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: ${{env.TF_VERSION}}

            - name: Terraform fmt check
              run: |
                    cd ${{ env.TF_PATH}}
                    terraform fmt --check


            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ env.AWS_REGION }} 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
            
            - name: initiailise terraform
              run: |
                cd ${{ env.TF_PATH}}
                terraform init
                
            - name: Check Terraform provider versions
              working-directory: ${{ env.TF_PATH }}
              run: |
                terraform version
                terraform providers
                cat .terraform.lock.hcl

            - name: $ {{ inputs.plan_apply_destroy }} terraform
              if : ${{ inputs.plan_apply_destroy == 'plan' }}
              working-directory: ${{ env.TF_PATH}}
              timeout-minutes: 10
              env:
                TF_LOG: INFO
              run: |
                echo "Starting Terraform plan..."
                terraform plan -input=false -no-color -lock-timeout=5m
                echo "Terraform plan completed successfully."

            - name: $ {{ inputs.plan_apply_destroy }} terraform
              if : ${{ inputs.plan_apply_destroy == 'apply' }} 
              working-directory: ${{ env.TF_PATH}}
              env:
                TF_LOG: INFO
              run: |
                echo "Starting Terraform apply..."
                terraform apply -input=false -auto-approve -no-color -lock-timeout=5m
                echo "Terraform apply completed successfully." 
            
            - name: $ {{ inputs.plan_apply_destroy }} terraform
              if : ${{ inputs.plan_apply_destroy == 'destroy' }} 
              working-directory: ${{ env.TF_PATH}}
              env:
                TF_LOG: INFO
              run: |
                echo "Starting Terraform destroy..."
                terraform destroy -input=false -auto-approve -no-color -lock-timeout=5m
                echo "Terraform destroy completed successfully." 

